/**
 * QuickJS Plugin Type Definitions
 * Auto-generated by the Plugin Loader.
 */

/**
 * The Host API allows plugins to interact with the server's storage.
 */
declare const Host: {
    storage: {
        /**
         * Retrieve a string value from the plugin's private storage.
         * Returns an empty string "" if the key does not exist (never undefined).
         * @param key The unique key for the value.
         */
        get(key: string): string;

        /**
         * Save a string value to the plugin's private storage.
         * @param key The unique key for the value.
         * @param value The string value to store.
         */
        set(key: string, value: string): void;

        /**
         * Delete a key from the plugin's private storage.
         * @param key The unique key to delete.
         */
        delete(key: string): void;

        /**
         * List all keys starting with the given prefix.
         * @param prefix The prefix to filter keys by.
         * @returns An array of matching keys.
         */
        list(prefix: string): string[];

        /**
         * Sanitize HTML content to prevent XSS.
         * Uses the server-side bluemonday policy.
         * @param html The dirty HTML string.
         * @returns The sanitized HTML string.
         */
        sanitize(html: string): string;
    };
};

/**
 * Minimal Console interface for the plugin environment.
 * Shimmed by the runtime to output to the server stdout.
 */
declare const console: {
    log(...args: any[]): void;
    error(...args: any[]): void;
    warn(...args: any[]): void;
    info(...args: any[]): void;
};

/**
 * Context data passed from the Go server to the plugin.
 * The structure depends on what the server injects.
 */
interface Context {
    // Common fields usually injected by handlers
    User?: {
        role: number;
        email: string;
        name: string;
        [key: string]: any;
    };
    Slug?: string;
    RequestID?: string;
    QueryParams?: Record<string, string[]>;

    // Allow any other properties
    [key: string]: any;
}

/**
 * Hook: onArticleRender
 * Called when the article content is ready to be rendered.
 * @param html The current HTML string of the article.
 * @param ctx The request context containing user info, etc.
 * @returns The modified HTML string.
 */
declare function onArticleRender(html: string, ctx: Context): string;

/**
 * Hook: onAction
 * Called when a client POSTs to /api/plugin/{pluginID}/{action}.
 * @param action The action name from the URL.
 * @param payload The JSON parsed body of the request.
 * @param ctx The request context containing user info, etc.
 * @returns A JSON-serializable object response.
 */
declare function onAction(action: string, payload: any, ctx: Context): any;